apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
type: Opaque
data:
  azurestorageaccountname: a3ViZXN0b3JhZ2U=
  azurestorageaccountkey: MnNQUmYycVNmVTBEZ2JPUVBveXRnR0pnTWRYQ0NkRHRlQmU1TExtRVdidWt3Y1RZQjRpK2s1RVVZRjdEV2NDdVU4NEhUT2ZuSlY2cDlvU1hpeEZZOXc9PQ==
