apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30808
  - name: jnlp
    protocol: TCP
    port: 5000
    nodePort: 30500